project:
  type: website

website:
  title: "Data-Based Economics"
  search: false
  sidebar:
      style: "docked"
      contents:
        - section: lectures
          contents:
            - slides/session_1/index.qmd
            - slides/session_2/index.qmd
            - slides/session_3/index.qmd

        # - section: tutorials
        #   contents:
        #     - tutorials/session_1/Exercises.ipynb
        #     - tutorials/session_1/Python_basics.ipynb

format:
  html:
    theme: default
    css: styles.css
    toc: true
